steps:
  - id: "Rodando docker compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f', 'docker-compose.cloudbuild.prod.yml', 'up', '-d']

  - id: "Rodando docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']

  - id: "Rodando compose"
    name: 'gcr.io/cloud-builders/docker'
    args: ['-t', 'app', 'composer install']
